import "./globals.css";
import type { Metadata } from "next";
import Navbar from "./components/navbar/Navbar";
import getCurrUser from "./actions/getCurrentUser";

export const metadata: Metadata = {
  title: "Blog 2.0",
  description: "Generated by Next.js",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const currentUser = await getCurrUser();
  return (
    <html lang="en">
      <body className={`bg-slate-950`}>
        <Navbar currentUser={currentUser} />
        {children}
      </body>
    </html>
  );
}
